// ─── Auth ────────────────────────────────────────────────────────────────────
//
// IMPORTANT: the real backend's /auth/login, /auth/register, /auth/refresh,
// and /auth/oauth/* endpoints return ONLY a token pair — never a `user`
// object (verified against internal/auth/handler.go). There is no GET /me
// endpoint either. The only user identity available client-side comes from
// decoding the JWT payload (sub, org_id, role) — see utils/jwt.ts.

export interface AuthTokens {
  access_token: string
  refresh_token: string
  token_type: string
  expires_in: number
}

/** Decoded from the JWT payload — see internal/middleware/auth.go claims: sub, org_id, role. */
export interface DecodedUser {
  id: string       // claims.sub
  org_id: string   // claims.org_id
  role: 'admin' | 'employee'  // claims.role — backend only ever sets these two (see internal/auth/service.go)
}

export interface AuthState {
  user: DecodedUser | null
  accessToken: string | null
  refreshToken: string | null
  isAuthenticated: boolean
}

// ─── Organization ─────────────────────────────────────────────────────────────
//
// Real shape per internal/model/organization.go — NO settings field exists
// on the backend. Any language/timezone/reply-style preference is stored
// client-side only (see store/index.ts useLocalSettingsStore).

export interface Organization {
  id: string
  name: string
  slug: string
  plan: 'free' | 'pro' | 'enterprise'
  created_at: string
}

// ─── Incoming Events ──────────────────────────────────────────────────────────
//
// source includes 'gmail' on the real backend (internal/model/events.go),
// in addition to email/api/webhook.

export type EventSource = 'email' | 'api' | 'webhook' | 'gmail'
export type EventStatus = 'new' | 'processing' | 'completed' | 'failed'
export type ActionType = 'schedule_meeting' | 'create_task' | 'analyze_document' | 'send_email_draft'
export type ActionStatus = 'success' | 'failed' | 'skipped'

export interface EventAttachment {
  filename: string
  content_type: string
  size: number
  url: string
}

export interface EventMetadata {
  sender?: string
  subject?: string
  // The real backend can store this as `null` (confirmed in simulation-report.md
  // when an email has no attachments) rather than an empty array or undefined.
  attachments?: EventAttachment[] | null
  headers?: Record<string, string>
}

export interface IncomingEvent {
  id: string
  org_id: string
  source: EventSource
  raw_content: string
  metadata: EventMetadata
  status: EventStatus
  created_at: string
}

/**
 * Shape of GET /api/v1/events/:id. NOTE: `analysis` and `action_logs` are
 * OMITTED from the JSON entirely (not present as keys) when there's nothing
 * to show yet — not set to null. Always use `event.analysis ?? null` /
 * `event.action_logs ?? []` defensively, never assume the key exists.
 */
export interface FullEvent {
  event: IncomingEvent
  analysis?: AIAnalysis
  action_logs?: ActionLog[]
}

// ─── AI Analysis ──────────────────────────────────────────────────────────────
//
// `intent` is a free-form string generated by the LLM (see internal/ai/client.go
// system prompt: "a short label describing the email's purpose") — never
// treat it as a fixed enum in the UI; only `actions[].type` is constrained.

export interface AIAction {
  type: ActionType
  data: Record<string, unknown>
}

export interface AIAnalysis {
  id: string
  event_id: string
  org_id: string
  version: number
  intent: string
  confidence: number
  actions: AIAction[]
  raw_response: Record<string, unknown>
  created_at: string
}

// ─── Action Logs ──────────────────────────────────────────────────────────────

export interface ActionLog {
  id: string
  org_id: string
  event_id: string
  action_type: ActionType
  payload: Record<string, unknown>
  status: ActionStatus
  error_message?: string | null
  created_at: string
}

// ─── Tasks ────────────────────────────────────────────────────────────────────
//
// The `tasks.status` column has NO check constraint on the backend
// (internal/db/migrations/000001_init.up.sql) — any string the client sends
// via PATCH is stored verbatim. The SQL DEFAULT is 'new' (confirmed — the
// swagger annotation saying "pending" is stale/inaccurate and doesn't match
// the actual INSERT statement in internal/actions/handlers_task.go). We use
// 'new' | 'in_progress' | 'done' | 'cancelled' consistently across the app.

export type TaskStatus = 'new' | 'in_progress' | 'done' | 'cancelled'

export interface Task {
  id: string
  org_id?: string
  /** Null for manually-created tasks (via POST /tasks) — only AI-created tasks have an originating event. */
  event_id?: string | null
  assignee_id?: string | null
  title: string
  description?: string | null
  status: TaskStatus
  due_date?: string | null
  /** Set when status transitions to done/cancelled (migration 000005). Used by analytics for on-time calculations. */
  completed_at?: string | null
  created_at: string
}

// ─── Document Analysis ────────────────────────────────────────────────────────
//
// CRITICAL: the shape of `risks` is DIFFERENT depending on the endpoint.
// - GET /events/:id/documents (list)  → risks is a NUMBER (count only).
//   Verified in internal/documents/handler.go: `Risks int`.
// - The full risk strings are NOT separately exposed by any endpoint — only
//   the count. If risk detail is ever needed, it would have to come from
//   `analysis.raw_response`, which is not guaranteed to contain it either.

export interface DocumentAnalysisListItem {
  id: string
  file_name: string
  summary?: string | null
  risks: number
  analyzed_at: string
}

// ─── Drafts ───────────────────────────────────────────────────────────────────

export type DraftStatus = 'pending_approval' | 'approved' | 'sent' | 'rejected'

export interface DraftListItem {
  id: string
  event_id: string
  recipient: string
  subject: string
  status: DraftStatus
  created_at: string
}

/** Full draft shape returned by GET /drafts/:id — includes `body`, list items don't. */
export interface Draft extends DraftListItem {
  org_id: string
  body: string
}

export interface DraftApproveResponse {
  id: string
  status: DraftStatus
  send_status?: 'success' | 'failed'
  send_error?: string
}

// ─── Calendar Events ──────────────────────────────────────────────────────────
//
// Synthesized server-side from action_logs where action_type='schedule_meeting'
// — there's no calendar_events table. No `event_id` field is actually present
// on each item (see internal/email/analysis_handler.go GetCalendarEvents).

export interface CalendarEventItem {
  title: string
  datetime: string
  google_event_id?: string
  status: 'created' | 'failed'
  created_at: string
}

// ─── Integrations ──────────────────────────────────────────────────────────────

export type IntegrationProvider = 'gmail' | 'calendar'

export interface IntegrationStatus {
  provider: IntegrationProvider
  connected: boolean
  scope?: string
}

// ─── API Responses ────────────────────────────────────────────────────────────
//
// NOTE: the real backend never returns `has_more` — only data/total/page/per_page.
// Compute "has more" on the client as `page * per_page < total` where needed.

export interface PaginatedResponse<T> {
  data: T[]
  total: number
  page: number
  per_page: number
}

export interface ApiError {
  error: string
  message?: string
}

// ─── Filters ─────────────────────────────────────────────────────────────────

export interface EventFilters {
  status?: EventStatus | 'all'
  page?: number
  per_page?: number
}

export interface TaskFilters {
  status?: TaskStatus | 'all'
  page?: number
  per_page?: number
}

export interface DraftFilters {
  status?: DraftStatus | 'all'
  page?: number
  per_page?: number
}

// ─── Local-only Settings (never sent to backend) ─────────────────────────────
//
// The backend has no concept of these — purely a client preference persisted
// to localStorage via store/index.ts useLocalSettingsStore.

export interface LocalSettings {
  language: 'en' | 'ru' | 'kk'
  replyStyle: 'formal' | 'neutral' | 'friendly'
}

// ─── Insights ─────────────────────────────────────────────────────────────────
//
// GET /insights computes these on-demand from real data using deterministic
// rules (internal/insights/rules.go) — no LLM call, no insights table. `key`
// is required to call PATCH /insights/resolve since insights have no other
// stable identifier.

export type InsightType = 'overdue_task' | 'draft_pending_too_long' | 'unassigned_task' | 'action_failure_spike'
export type InsightSeverity = 'critical' | 'warning' | 'info'

export interface Insight {
  key: string
  type: InsightType
  severity: InsightSeverity
  title: string
  description: string
  created_at: string
  is_resolved: boolean
}

// ─── Analytics ────────────────────────────────────────────────────────────────
//
// GET /analytics/summary — every field is computed from real tables (see
// internal/analytics/repository.go). ai_accuracy_pct is explicitly an
// approximation (average LLM confidence, not verified accuracy); the
// has_on_time_data flag tells you whether tasks_on_time_pct has any
// real samples behind it yet.

export interface AnalyticsSummary {
  events_today: number
  events_auto_processed: number
  active_tasks: number
  overdue_tasks: number
  open_documents: number
  tasks_on_time_pct: number
  has_on_time_data: boolean
  ai_accuracy_pct: number
  ai_accuracy_is_approximation: boolean
}
